### ISSUE TITLE
Feature Request: VenterToggle

### ISSUE THREAD

**Issue by pyrho** [JMcKiern/vim-venter#1]
Hi !

Thank you for Venter!
Would it be possible to add a toggle option, I'd like to bind Venter to a single mapping.

Thanks!

**Comment by JMcKiern** [comment]
Ah yes, good idea!
I'll add that tomorrow when I get a chance

**Comment by JMcKiern** [comment]
Closed by 469f1dfea67748e88816fd31daf6ca0c919b27c3
