### ISSUE TITLE
E154: Duplicate tag "venter" in file

### ISSUE THREAD

**Issue by lacava** [JMcKiern/vim-venter#10]
helptags seems to complain about the two "venter" lines in `venter.txt` when running `PluginInstall'. I'm using Vundle, vim 8.0 on ubuntu 18.04. 

When running `:PluginInstall', I get: 

> [2021-11-03 10:02:13] > Error running :helptags /home/bill/.vim/bundle/vim-venter/doc

if I run ':helptags /home/bill/.vim/bundle/vim-venter/doc', I get:

> E154: Duplicate tag "venter" in file /home/bill/.vim/bundle/vim-venter/doc/venter.txt

Changing `*venter*` to `*Venter*` on line 2 of venter.txt seems to fix the issue.

**Comment by JMcKiern** [comment]
Closed by #12
