### ISSUE TITLE
Feature request: Toggle on automatically based on the quantity of splits

### ISSUE THREAD

**Issue by lourenci** [JMcKiern/vim-venter#2]
What if the plugin would open itself on a tab without windows and closes itself when more than one window is opened?

**Comment by JMcKiern** [comment]
Sorry, I've been quite busy over the last while.

To solve your first request, you could add a `:newtab` command before calling Venter.

The second one would require a code change. I will try to get around to it but it will be at least a few weeks. 

Feel free to make a pr in the meantime
