### ISSUE TITLE
Set single central window width to textwidth and add adjust padding windows accordingly

### ISSUE THREAD

**Issue by kiryph** [JMcKiern/vim-venter#3]
Quote from README.md:

> This is mainly useful when working with one file on a large monitor

I use venter in this scenario. I would prefer that the window width showing the file is adjusted to the current textwidth (set by modeline, by a filetype plugin, [editorconfig](https://editorconfig.org/) file, etc.).
.
Currently, `g:venter_width` sets the padding windows and not the main window.

**Comment by JMcKiern** [comment]
Hey, sorry for the delay. I have added a PR to make this change. Would you mind checking if the `textwidth` branch does what you're expecting. Thanks

**Comment by kiryph** [comment]
@JMcKiern I have checked out the branch "textwidth".

And yes, it does what I expect. Thank you. Do you merge it into master?

**Comment by JMcKiern** [comment]
Great, thanks. I'll merge to master now
