### ISSUE TITLE
Error E417 when using `:VenterClose` or `:VenterToggle` with `g:venter_disable_vertsplit`

### ISSUE THREAD

**Issue by bustinbung** [JMcKiern/vim-venter#9]
Works fine with `g:venter_disable_vertsplit` disabled, but throws this error when enabled:
```
Error detected while processing function venter#VenterToggle[2]..VenterClose[13]..<SNR>119_CheckWinIds:                                                                             
line   32:
E417: missing argument: ctermbg=
Press ENTER or type command to continue
```
It still works to disable venter, but the extra keypress is annoying.

**Comment by JMcKiern** [comment]
Sorry about that, I think the commit above should have fixed it.

**Comment by bustinbung** [comment]
Can confirm that fixed it, thanks!

**Comment by bustinbung** [comment]
The error recently cropped up again, and I'm not sure if it's an issue with venter or an issue with the new setup I'm using.

```
Error detected while processing function venter#VenterToggle[2]..VenterClose[13]..<SNR>97_CheckWinIds:
line   33:
E421: Color name or number not recognized: ctermbg=#517F8D
Press ENTER or type command to continue
```
System Information:
+ Manjaro Linux
+ Alacritty with palette set to `base16_atlas`
+ zsh

**Comment by bustinbung** [comment]
Manually setting the `ctermbg` value to `0` or `none` seems to resolve the error, but doesn't remove the vertical split. Unsure how to fix this issue—is there way to get the background color of the terminal and set the characters to that color?
